In [1]:
import pandas as pd

In [498]:
full_data = pd.read_csv("./full_data.csv")
full_data.drop_duplicates(keep='first', inplace=True)
print(full_data.shape)

(1993, 12)

In [499]:
full_data.dropna(subset=['category'], inplace=True)
full_data.reset_index(drop=True, inplace=True)

In [500]:
full_data = full_data.drop('piece', 1)
full_data = full_data.drop('chambres', 1)
full_data = full_data.drop('area', 1)
full_data

,category,localite,price,monthly,description,Diagnostic de performance énergétique(kWhEP/m².an),Indice d'émission de gaz à effet de serre(kgeqCO2/m².an),plus,type
0,Maison / Villa,Quartier <!-- -->Le Lac-Briques Rouges<!-- -->...,349 500 €,1 449 €,"style=""max-height: 66px;""><p>Belle maison en s...",150.0,35.0,"['1 Terrasse', 'Cheminée', 'Surface de 105m²',...",Acheter
1,Maison / Villa,"Quartier <!-- -->Centre Ville<!-- -->, <!-- --...",335 000 €,1 389 €,"style=""max-height: 66px;""><p>Idéalement situé ...",NaN,NaN,"['1 Terrasse', 'Cheminée', 'Surface de 185m²',...",Acheter
2,Maison / Villa,"Quartier <!-- -->Vinaigrier<!-- -->, <!-- -->Nice",2 490 000 €,10 270 €,"style=""max-height: 66px;""><p>Superbe Villa dan...",99.0,19.0,"['Orientation Sud', '1 Balcon', 'Vue', 'Piscin...",Acheter
3,Maison / Villa,"Quartier <!-- -->Sud<!-- -->, <!-- -->Gouvieux",356 000 €,1 476 €,"style=""max-height: 66px;""><p>A découvrir à 5km...",NaN,NaN,"['Cheminée', 'Surface de 130m²', 'Bâtiment de ...",Acheter
4,Maison / Villa,"Quartier <!-- -->Centre Ville<!-- -->, <!-- --...",388 500 €,1 610 €,"style=""max-height: 66px;""><p>MAISON INDIVIDUEL...",214.0,11.0,"['1 Terrasse', 'Surface de 102m²', '6 Pièces',...",Acheter
...,...,...,...,...,...,...,...,...,...
1987,Maison / Villa,Villeparisis,148 000 €,619 €,NaN,216.0,11.0,"['1 Terrasse', 'Cheminée', 'Surface de 127m²',...",Acheter
1988,Maison / Villa,Carnac,75 240 €,317 €,NaN,305.0,NaN,"['Cheminée', 'Surface de 140m²', '5 Pièces', '...",Acheter
1989,Appartement,Mandelieu-la-Napoule,375 000 €,1 554 €,NaN,167.0,7.0,"['Orientation Sud-Ouest', 'Cave', '1 Terrasse'...",Acheter
1990,Appartement,Hyères,520 000 €,2 152 €,NaN,125.0,3.0,"['Orientation Sud', '1 Terrasse', 'Ascenseur',...",Acheter
1991,Appartement,Torcy,213 300 €,888 €,NaN,153.0,33.0,"['Surface de 56m²', 'Bâtiment de 2 étages', '3...",Acheter

In [501]:
full_data.rename({'price': 'price(€)'}, axis=1, inplace=True)
full_data.rename({'monthly': 'monthly(€)'}, axis=1, inplace=True)

In [502]:
full_data['localite'] = full_data['localite'].str.replace("'",' ')
full_data.dropna(subset = ['localite'], inplace = True)

full_data['localite'] = full_data['localite'].str.replace('é','e')
full_data['localite'] = full_data['localite'].str.replace('è','e')


full_data['price(€)'] = full_data['price(€)'].str.replace(' €','')
full_data['price(€)'] = full_data['price(€)'].str.replace('€','')
full_data['price(€)'] = full_data['price(€)'].str.replace('<iclass="evol-price-labelfifi-arrow-up-right"></i>','')
full_data['price(€)'] = full_data['price(€)'].str.replace('<iclass="evol-price-labelfifi-arrow-down-right"></i>','')
full_data['price(€)'] = full_data['price(€)'].str.replace('<spanclass="bouquet">Bouquet</span>','')
full_data['price(€)'] = full_data['price(€)'].str.replace(' ','')

full_data['monthly(€)'] = full_data['monthly(€)'].str.replace(' €','')
full_data['monthly(€)'] = full_data['monthly(€)'].str.replace('€','')
full_data['monthly(€)'] = full_data['monthly(€)'].str.replace('À partir de ','')
full_data['monthly(€)'] = full_data['monthly(€)'].str.replace(' / mois','')

full_data['category'] = full_data['category'].str.replace('<!-- --> en viager','')

full_data['description'] = full_data['description'].str.replace('style="max-height: 66px;"><p>','')
full_data['description'] = full_data['description'].str.replace('<p>','')
full_data['description'] = full_data['description'].str.replace('<butto','')
full_data['description'] = full_data['description'].str.replace('\r','')
full_data['description'] = full_data['description'].str.replace('</p>','')
full_data['plus'] = full_data['plus'].str.replace('[','')
full_data['plus'] = full_data['plus'].str.replace(']','')
full_data['plus'] = full_data['plus'].str.replace("'",'')
full_data['plus'] = full_data['plus'].str.replace('"','')

full_data['localite'] = full_data['localite'].str.replace('Quartier <!-- -->','')
full_data['localite'] = full_data['localite'].str.replace('<!-- -->','')

full_data

,category,localite,price(€),monthly(€),description,Diagnostic de performance énergétique(kWhEP/m².an),Indice d'émission de gaz à effet de serre(kgeqCO2/m².an),plus,type
0,Maison / Villa,"Le Lac-Briques Rouges, Vigneux-sur-Seine",349500,1 449,Belle maison en sous/bassement meulière très b...,150.0,35.0,"1 Terrasse, Cheminée, Surface de 105m², 5 Pièc...",Acheter
1,Maison / Villa,"Centre Ville, Clermont-l Herault",335000,1 389,Idéalement situé entre Clermont l'Hérault et L...,NaN,NaN,"1 Terrasse, Cheminée, Surface de 185m², 5 Pièc...",Acheter
2,Maison / Villa,"Vinaigrier, Nice",2490000,10 270,Superbe Villa dans les hauteurs de Nice/Villef...,99.0,19.0,"Orientation Sud, 1 Balcon, Vue, Piscine, Surfa...",Acheter
3,Maison / Villa,"Sud, Gouvieux",356000,1 476,"A découvrir à 5km de Gouvieux, maison ancienne...",NaN,NaN,"Cheminée, Surface de 130m², Bâtiment de 1 étag...",Acheter
4,Maison / Villa,"Centre Ville, Plaisir",388500,1 610,MAISON INDIVIDUELLE DE 6 PIÈCES A VENDRE A PLA...,214.0,11.0,"1 Terrasse, Surface de 102m², 6 Pièces, 4 Cham...",Acheter
...,...,...,...,...,...,...,...,...,...
1987,Maison / Villa,Villeparisis,148000,619,NaN,216.0,11.0,"1 Terrasse, Cheminée, Surface de 127m², 5 Pièc...",Acheter
1988,Maison / Villa,Carnac,75240,317,NaN,305.0,NaN,"Cheminée, Surface de 140m², 5 Pièces, 2 Chambr...",Acheter
1989,Appartement,Mandelieu-la-Napoule,375000,1 554,NaN,167.0,7.0,"Orientation Sud-Ouest, Cave, 1 Terrasse, Pisci...",Acheter
1990,Appartement,Hyeres,520000,2 152,NaN,125.0,3.0,"Orientation Sud, 1 Terrasse, Ascenseur, Surfac...",Acheter
1991,Appartement,Torcy,213300,888,NaN,153.0,33.0,"Surface de 56m², Bâtiment de 2 étages, 3 Pièce...",Acheter

In [503]:
plus = list(full_data['plus'])
plus = str(plus)
plus = plus.split("'")
length=len(plus)-1
i=0
while(i<=length):
    if(plus[i]=="[" or plus[i]=="]" or plus[i]==", "):
        plus.pop(i)
        length-=1
    i+=1
len(plus)

1992

In [504]:
terrasse = []   # 1 Terrasse
vue = []        # Vue (1, 0)
surface = []    # Surface de 200m²
piece = []      # 7 Pièces
chambre = []    # 6 Chambres
annee_de_construction = []       # Année de construction 1975
salle_de_bain = []               # 1 Salle de bain
salles_deau = []                 # 2 Salles deau
toilettes = []                   # 3 Toilettes
cuisine_equipee = []             # Cuisine équipée (1, 0)
surface_salle_de_sejour = []     # Salle de séjour : 50m²
terrain_de = []       # Terrain de 1770m²
boxs = []             # 3 Boxs
cave = []             # Cave (1, 0)
gardien = []          # Gardien (1, 0)
ascenseur = []        # Ascenseur (1, 0)
batiment_de = []      # Bâtiment de 11 étages
etage = []            # Au 8ème étage
rangements = []                # Rangements (1, 0)
cuisine_americaine = []        # Cuisine américaine (1, 0) ou Cuisine américaine équipée
une_entree = []             # Une entrée (1, 0)
salle_de_sejour = []        # Salle de séjour (1, 0)
interphone = []             # Interphone (1, 0)
piscine = []                # Piscine (1, 0)
cheminee = []               # Cheminée (1, 0)
parquet = []                # Parquet (1, 0)
cuisine_aucune = []         # Cuisine aucune (1, 0)
calme = []                  # Calme (1, 0)
cuisine_separee = []        # Cuisine séparée (1, 0)
travaux = []                # Travaux (1, 0)
refait_a_neuf = []          # Refait à neuf (1, 0)
toilette_separee = []       # Toilette séparée (1, 0)
digicode = []               # Digicode (1, 0)
parking = []            # 1 Parking
salle_a_manger = []              # Salle à manger (1, 0)
adapte_pmr = []                  # Adapté PMR (1, 0)
terrain_constructible = []       # Terrain constructible (1, 0)
viabilise = []                   # Viabilisé (1, 0)
surface_balcon = []
nombre_balcon = []
surface_cave = []

orientation_est = []        # Orientation Est (1, 0)
orientation_nord = []            # Orientation Nord (1, 0)
orientation_sud = []        # Orientation Sud (1, 0)
orientation_ouest = []      # Orientation Ouest (1, 0)
orientation_Sud_Ouest = []
orientation_Sud_Est = []
orientation_Nord_Ouest = []
orientation_Nord_Est = []

chauffage_fuel = []   # Chauffage individuel fuel (0, 1)
chauffage_gaz = []      # Chauffage individuel gaz (1, 0)
chauffage_electrique = []   # Chauffage individuel électrique (1, 0)
chauffage_central = []         # Chauffage central (1, 0)
chauffage_radiateur = []
chauffage_mixte = []
chauffage_sol = []
chauffage_individuel = []        # Chauffage individuel (1, 0)
chauffage_collectif = []
chauffage_climatisation = []
chauffage_reversible = []

travaux_a_prevoir = []
situation = []                   # Situation : ville
recent = []                      # Récent (1, 0)
alarme = []                      # Alarme (0, 1)
meuble = []                      # Meublé (0, 1)
television = []                  # Télévision (0, 1)
cuisine_coin_cuisine = []        # Cuisine coin cuisine (0, 1)

In [505]:
def model_num_name (plus, list_data, ch):
    for i in range (len(plus)):
        L=plus[i].split(", ")
        b=0
        for j in range (len(L)):
            if (ch in L[j] and "séparé" not in L[j].lower()):
                list_data.append(L[j])
                b=1
            if(j==len(L)-1 and b==0):
                list_data.append("0")
                
def model_1_0 (plus, list_data, ch):
    for i in range (len(plus)):
        L=plus[i].split(", ")
        b=0
        for j in range (len(L)):
            if (ch in L[j] and "m²" not in L[j]):
                list_data.append(L[j])
                b=1
            if(j==len(L)-1 and b==0):
                list_data.append("0")
                
def model_1_0_v2 (plus, list_data, ch):
    for i in range (len(plus)):
        L=plus[i].split(", ")
        b=0
        for j in range (len(L)):
            if (ch in L[j] and "-" not in L[j]):
                list_data.append(L[j])
                b=1
            if(j==len(L)-1 and b==0):
                list_data.append("0")

                
            
for i in range (len(plus)):
    L=plus[i].split(", ")
    b=0
    for j in range (len(L)):
        if ("m² Balcon" in L[j] or "Balcon de" in L[j]):
            surface_balcon.append(L[j])
            b=1
        if(j==len(L)-1 and b==0):
            surface_balcon.append("0")

for i in range (len(plus)):
    L=plus[i].split(", ")
    b=0
    for j in range (len(L)):
        if ("m² Balcon" not in L[j] and "Balcon de" not in L[j] and "Balcon" in L[j]):
            nombre_balcon.append(L[j])
            b=1
        if(j==len(L)-1 and b==0):
            nombre_balcon.append("0")

for i in range (len(plus)):
    L=plus[i].split(", ")
    b=0
    for j in range (len(L)):
        if ("m² Cave" not in L[j] and "Cave de" not in L[j] and "Cave" in L[j]):
            cave.append(L[j])
            b=1
        if(j==len(L)-1 and b==0):
            cave.append("0")

            
for i in range (len(plus)):
    L=plus[i].split(", ")
    b=0
    for j in range (len(L)):
        if ("m² Cave" in L[j] or "Cave de" in L[j]):
            surface_cave.append(L[j])
            b=1
        if(j==len(L)-1 and b==0):
            surface_cave.append("0")


model_num_name(plus, terrasse, "Terrasse")
model_num_name(plus, piece, "Pièce")
model_num_name(plus, chambre, "Chambre")
model_num_name(plus, salle_de_bain, "de bain")
model_num_name(plus, salles_deau, "deau")
model_num_name(plus, boxs, "Box")
model_num_name(plus, parking, "Parking")
model_num_name(plus, situation, "Situation")
    
model_1_0(plus, vue, "Vue")
model_1_0(plus, gardien, "Gardien")
model_1_0(plus, ascenseur, "Ascenseur")
model_1_0(plus, rangements, "Rangements")
model_1_0(plus, une_entree, "Une entrée")
model_1_0(plus, salle_de_sejour, "Salle de séjour")
model_1_0(plus, interphone, "Interphone")
model_1_0(plus, piscine, "Piscine")
model_1_0(plus, cheminee, "Cheminée")
model_1_0(plus, parquet, "Parquet")
model_1_0(plus, calme, "Calme")
model_1_0(plus, travaux, "Travaux")
model_1_0(plus, travaux_a_prevoir, "Travaux À Prévoir")
model_1_0(plus, refait_a_neuf, "Refait à neuf")
model_1_0(plus, digicode, "Digicode")
model_1_0(plus, salle_a_manger, "Salle à manger")
model_1_0(plus, recent, "Récent")
model_1_0(plus, alarme, "Alarme")
model_1_0(plus, meuble, "Meublé")
model_1_0(plus, television, "Télévision")

model_1_0(plus, adapte_pmr, "Adapté PMR")
model_1_0(plus, terrain_constructible, "Terrain constructible")
model_1_0(plus, viabilise, "Viabilisé")

model_1_0_v2(plus, orientation_nord, "Orientation Nord")
model_1_0_v2(plus, orientation_sud, "Orientation Sud")
model_1_0_v2(plus, orientation_est, "Orientation Est")
model_1_0_v2(plus, orientation_ouest, "Orientation Ouest")
model_1_0(plus, orientation_Sud_Ouest, "Orientation Sud-Ouest")
model_1_0(plus, orientation_Sud_Est, "Orientation Sud-Est")
model_1_0(plus, orientation_Nord_Ouest, "Orientation Nord-Ouest")
model_1_0(plus, orientation_Nord_Est, "Orientation Nord-Est")

model_1_0(plus, chauffage_gaz, "gaz")
model_1_0(plus, chauffage_radiateur, "radiateur")
model_1_0(plus, chauffage_mixte, "mixte")
model_1_0(plus, chauffage_electrique, "électrique")
model_1_0(plus, chauffage_fuel, "fuel")
model_1_0(plus, chauffage_central, "central")
model_1_0(plus, chauffage_individuel, "individuel")
model_1_0(plus, chauffage_sol, "sol")
model_1_0(plus, chauffage_collectif, "collectif")
model_1_0(plus, chauffage_climatisation, "climatisation")
model_1_0(plus, chauffage_reversible, "réversible")
 

model_1_0(plus, cuisine_separee, "Cuisine séparée")
model_1_0(plus, cuisine_americaine, "américaine")
model_1_0(plus, cuisine_equipee, "équipée")
model_1_0(plus, cuisine_aucune, "aucune")
model_1_0(plus, cuisine_coin_cuisine, "coin cuisine")

model_1_0(plus, toilette_separee, "Toilette séparée")
model_num_name(plus, toilettes, "Toilette")

model_num_name(plus, surface, "Surface de")
model_num_name(plus, surface_salle_de_sejour, "Salle de séjour :")
model_num_name(plus, terrain_de, "Terrain de")
model_num_name(plus, batiment_de, "Bâtiment de")
model_num_name(plus, etage, "Au")
model_num_name(plus, annee_de_construction, "Année de construction")

In [506]:
full_data = full_data.drop('plus', 1)

In [507]:
full_data["terrasse"] = terrasse
full_data["vue"] = vue
full_data["surface"] = surface
full_data["piece"] = piece
full_data["chambre"] = chambre
full_data["annee_de_construction"] = annee_de_construction
full_data["salle_de_bain"] = salle_de_bain
full_data["salles_deau"] = salles_deau
full_data["surface_salle_de_sejour"] = surface_salle_de_sejour
full_data["terrain_de"] = terrain_de
full_data["boxs"] = boxs
full_data["cave"] = cave
full_data["gardien"] = gardien
full_data["ascenseur"] = ascenseur
full_data["batiment_de"] = batiment_de
full_data["etage"] = etage
full_data["rangements"] = rangements
full_data["une_entree"] = une_entree
full_data["salle_de_sejour"] = salle_de_sejour
full_data["interphone"] = interphone
full_data["piscine"] = piscine
full_data["cheminee"] = cheminee
full_data["parquet"] = parquet
full_data["calme"] = calme
full_data["travaux"] = travaux
full_data["travaux_a_prevoir"] = travaux_a_prevoir
full_data["refait_a_neuf"] = refait_a_neuf
full_data["digicode"] = digicode
full_data["parking"] = parking
full_data["salle_a_manger"] = salle_a_manger
full_data["adapte_pmr"] = adapte_pmr
full_data["terrain_constructible"] = terrain_constructible
full_data["viabilise"] = viabilise
full_data["surface_balcon"] = surface_balcon
full_data["nombre_balcon"] = nombre_balcon
full_data["surface_cave"] = surface_cave
full_data["situation"] = situation
full_data["recent"] = recent
full_data['alarme'] = alarme
full_data['meuble'] = meuble
full_data['television'] = television

full_data["toilettes"] = toilettes
full_data["toilette_separee"] = toilette_separee

full_data["cuisine_separee"] = cuisine_separee
full_data["cuisine_aucune"] = cuisine_aucune
full_data["cuisine_americaine"] = cuisine_americaine
full_data["cuisine_equipee"] = cuisine_equipee
full_data["cuisine_coin_cuisine"] = cuisine_coin_cuisine

full_data["orientation_nord"] = orientation_nord
full_data["orientation_est"] = orientation_est
full_data["orientation_ouest"] = orientation_ouest
full_data["orientation_sud"] = orientation_sud
full_data["orientation_Sud_Ouest"] = orientation_Sud_Ouest
full_data["orientation_Sud_Est"] = orientation_Sud_Est
full_data["orientation_Nord_Ouest"] = orientation_Nord_Ouest
full_data["orientation_Nord_Est"] = orientation_Nord_Est

full_data["chauffage_radiateur"] = chauffage_radiateur
full_data["chauffage_gaz"] = chauffage_gaz
full_data["chauffage_mixte"] = chauffage_mixte
full_data["chauffage_electrique"] = chauffage_electrique
full_data["chauffage_fuel"] = chauffage_fuel
full_data["chauffage_central"] = chauffage_central
full_data["chauffage_individuel"] = chauffage_individuel
full_data["chauffage_sol"] = chauffage_sol
full_data["chauffage_collectif"] = chauffage_collectif
full_data["chauffage_climatisation"] = chauffage_climatisation
full_data["chauffage_reversible"] = chauffage_reversible

In [508]:
full_data['terrasse'] = full_data['terrasse'].str.replace(' Terrasses','')
full_data['terrasse'] = full_data['terrasse'].str.replace(' Terrasse','')
full_data['vue'] = full_data['vue'].str.replace('Vue','1')
full_data['surface'] = full_data['surface'].str.replace('Surface de ','')
full_data['surface'] = full_data['surface'].str.replace('m²','')
full_data.rename({'surface': 'surface(m²)'}, axis=1, inplace=True)
full_data['piece'] = full_data['piece'].str.replace(' Pièces','')
full_data['piece'] = full_data['piece'].str.replace(' Pièce','')
full_data['chambre'] = full_data['chambre'].str.replace(' Chambres','')
full_data['chambre'] = full_data['chambre'].str.replace(' Chambre','')
full_data['annee_de_construction'] = full_data['annee_de_construction'].str.replace('Année de construction ','')
full_data['salle_de_bain'] = full_data['salle_de_bain'].str.replace(' Salles de bain','')
full_data['salle_de_bain'] = full_data['salle_de_bain'].str.replace(' Salle de bain','')
full_data['salles_deau'] = full_data['salles_deau'].str.replace(' Salles deau','')
full_data['salles_deau'] = full_data['salles_deau'].str.replace(' Salle deau','')
full_data['surface_salle_de_sejour'] = full_data['surface_salle_de_sejour'].str.replace('Salle de séjour : ','')
full_data['surface_salle_de_sejour'] = full_data['surface_salle_de_sejour'].str.replace('m²','')
full_data.rename({'surface_salle_de_sejour': 'surface_salle_de_sejour(m²)'}, axis=1, inplace=True)
full_data['terrain_de'] = full_data['terrain_de'].str.replace('Terrain de ','')
full_data['terrain_de'] = full_data['terrain_de'].str.replace('m²','')
full_data['terrain_de'] = full_data['terrain_de'].str.replace(' ha','0000')
full_data.rename({'terrain_de': 'terrain_de(m²)'}, axis=1, inplace=True)
full_data['boxs'] = full_data['boxs'].str.replace(' Boxes','')
full_data['boxs'] = full_data['boxs'].str.replace(' Boxs','')
full_data['boxs'] = full_data['boxs'].str.replace(' Box','')
full_data['cave'] = full_data['cave'].str.replace('Cave','1')
full_data['gardien'] = full_data['gardien'].str.replace('Gardien','1')
full_data['ascenseur'] = full_data['ascenseur'].str.replace('Ascenseur','1')
full_data['batiment_de'] = full_data['batiment_de'].str.replace('Bâtiment de ','')
full_data['batiment_de'] = full_data['batiment_de'].str.replace(' étages','')
full_data['batiment_de'] = full_data['batiment_de'].str.replace(' étage','')
full_data.rename({'batiment_de': 'batiment_de_x_étage'}, axis=1, inplace=True)
full_data['etage'] = full_data['etage'].str.replace('Au ','')
full_data['etage'] = full_data['etage'].str.replace('er étage','')
full_data['etage'] = full_data['etage'].str.replace('ème étage','')
full_data['etage'] = full_data['etage'].str.replace('rez-de-chaussée','-1')
full_data.rename({'etage': 'num_etage'}, axis=1, inplace=True)
full_data['rangements'] = full_data['rangements'].str.replace('Rangements','1')
full_data['une_entree'] = full_data['une_entree'].str.replace('Une entrée','1')
full_data['salle_de_sejour'] = full_data['salle_de_sejour'].str.replace('Salle de séjour','1')
full_data['interphone'] = full_data['interphone'].str.replace('Interphone','1')
full_data['piscine'] = full_data['piscine'].str.replace('Piscine','1')
full_data['cheminee'] = full_data['cheminee'].str.replace('Cheminée','1')
full_data['parquet'] = full_data['parquet'].str.replace('Parquet','1')
full_data['calme'] = full_data['calme'].str.replace('Calme','1')
full_data['travaux'] = full_data['travaux'].str.replace('Travaux','1')
full_data['travaux'] = full_data['travaux'].str.replace('1 À Prévoir','0')
full_data["travaux_a_prevoir"] = full_data['travaux_a_prevoir'].str.replace('Travaux À Prévoir','1')
full_data['refait_a_neuf'] = full_data['refait_a_neuf'].str.replace('Refait à neuf','1')
full_data['digicode'] = full_data['digicode'].str.replace('Digicode','1')
full_data['parking'] = full_data['parking'].str.replace(' Parkings','')
full_data['parking'] = full_data['parking'].str.replace(' Parking','')
full_data['salle_a_manger'] = full_data['salle_a_manger'].str.replace('Salle à manger','1')
full_data['adapte_pmr'] = full_data['adapte_pmr'].str.replace('Adapté PMR','1')
full_data['terrain_constructible'] = full_data['terrain_constructible'].str.replace('Terrain constructible','1')
full_data['viabilise'] = full_data['viabilise'].str.replace('Viabilisé','1')
full_data['surface_balcon'] = full_data['surface_balcon'].str.replace('m² Balcon','')
full_data['surface_balcon'] = full_data['surface_balcon'].str.replace('Balcon de ','')
full_data['surface_balcon'] = full_data['surface_balcon'].str.replace(' m²','')
full_data.rename({'surface_balcon': 'surface_balcon(m²)'}, axis=1, inplace=True)
full_data['nombre_balcon'] = full_data['nombre_balcon'].str.replace(' Balcons','')
full_data['nombre_balcon'] = full_data['nombre_balcon'].str.replace(' Balcon','')
full_data['surface_cave'] = full_data['surface_cave'].str.replace('m² Cave','')
full_data['surface_cave'] = full_data['surface_cave'].str.replace('Cave de ','')
full_data['surface_cave'] = full_data['surface_cave'].str.replace(' m²','')
full_data.rename({'surface_cave': 'surface_cave(m²)'}, axis=1, inplace=True)

full_data['recent'] = full_data['recent'].str.replace('Récent','1')
full_data['alarme'] = full_data['alarme'].str.replace('Alarme','1')
full_data['meuble'] = full_data['meuble'].str.replace('Meublé','1')
full_data['television'] = full_data['television'].str.replace('Télévision','1')
full_data['television'] = full_data['television'].str.replace(' Par Câble','1')

full_data['cuisine_equipee'] = full_data['cuisine_equipee'].str.replace('Cuisine américaine équipée','1')
full_data['cuisine_equipee'] = full_data['cuisine_equipee'].str.replace('Cuisine équipée','1')
full_data['cuisine_equipee'] = full_data['cuisine_equipee'].str.replace('Cuisine séparée équipée','1')

full_data['cuisine_separee'] = full_data['cuisine_separee'].str.replace('Cuisine américaine équipée','1')
full_data['cuisine_separee'] = full_data['cuisine_separee'].str.replace('Cuisine séparée équipée','1')
full_data['cuisine_separee'] = full_data['cuisine_separee'].str.replace('Cuisine séparée','1')

full_data['cuisine_aucune'] = full_data['cuisine_aucune'].str.replace('Cuisine aucune','1')
full_data['cuisine_americaine'] = full_data['cuisine_americaine'].str.replace('Cuisine américaine équipée','1')
full_data['cuisine_americaine'] = full_data['cuisine_americaine'].str.replace('Cuisine américaine','1')

full_data['cuisine_coin_cuisine'] = full_data['cuisine_coin_cuisine'].str.replace('Cuisine coin cuisine équipé','1')
full_data['cuisine_coin_cuisine'] = full_data['cuisine_coin_cuisine'].str.replace('Cuisine coin cuisine','1')

full_data['toilette_separee'] = full_data['toilette_separee'].str.replace('Toilette séparée','1')
full_data['toilettes'] = full_data['toilettes'].str.replace(' Toilettes','')
full_data['toilettes'] = full_data['toilettes'].str.replace(' Toilette','')

full_data['orientation_ouest'] = full_data['orientation_ouest'].str.replace('Orientation Ouest','1')
full_data['orientation_nord'] = full_data['orientation_nord'].str.replace('Orientation Nord','1')
full_data['orientation_sud'] = full_data['orientation_sud'].str.replace('Orientation Sud','1')
full_data['orientation_est'] = full_data['orientation_est'].str.replace('Orientation Est','1')
full_data["orientation_Sud_Ouest"] = full_data['orientation_Sud_Ouest'].str.replace('Orientation Sud-Ouest','1')
full_data["orientation_Sud_Est"] = full_data['orientation_Sud_Est'].str.replace('Orientation Sud-Est','1')
full_data["orientation_Nord_Ouest"] = full_data['orientation_Nord_Ouest'].str.replace('Orientation Nord-Ouest','1')
full_data["orientation_Nord_Est"] = full_data['orientation_Nord_Est'].str.replace('Orientation Nord-Est','1')

def change_chauff(ch):
    full_data[ch] = full_data[ch].str.replace('Chauffage','1')
    full_data[ch] = full_data[ch].str.replace('individuelle','')
    full_data[ch] = full_data[ch].str.replace('individuel','')
    full_data[ch] = full_data[ch].str.replace('électrique','')
    full_data[ch] = full_data[ch].str.replace('fuel','')
    full_data[ch] = full_data[ch].str.replace('radiateur','')
    full_data[ch] = full_data[ch].str.replace('gaz','')
    full_data[ch] = full_data[ch].str.replace('mixte','')
    full_data[ch] = full_data[ch].str.replace('collectif','')
    full_data[ch] = full_data[ch].str.replace('sol','')
    full_data[ch] = full_data[ch].str.replace('central','')
    full_data[ch] = full_data[ch].str.replace('climatisation','')
    full_data[ch] = full_data[ch].str.replace('réversible','')
    full_data[ch] = full_data[ch].str.replace('   e','')
    

change_chauff('chauffage_radiateur')
change_chauff('chauffage_gaz')
change_chauff('chauffage_mixte')
change_chauff('chauffage_electrique')
change_chauff('chauffage_fuel')
change_chauff('chauffage_central')
change_chauff('chauffage_individuel')
change_chauff('chauffage_sol')
change_chauff('chauffage_collectif')
change_chauff('chauffage_climatisation')
change_chauff('chauffage_reversible')

In [509]:
L = str(list(full_data["localite"])).split("'")
length=len(L)-1
i=0
while(i<=length):
    if(L[i]=="[" or L[i]=="]" or L[i]==", "):
        L.pop(i)
        length-=1
    i+=1

city1 = []
city2 = []
for i in range(len(L)):
    L2 = L[i].split(", ")
    if(len(L2)==2):
        city1.append(L2[0])
        city2.append(L2[1])
    elif(len(L2)==1):
        city1.append("0")
        city2.append(L2[0])

In [510]:
full_data["region_1"] = city2
full_data["region_2"] = city1

In [511]:
full_data["situation"] = full_data["situation"].str.replace(': ','')

In [512]:
final_data = full_data.drop(['localite'], axis='columns')
final_data['price(€)'] = final_data['price(€)'].str.replace(' €','')
final_data["surface_salle_de_sejour(m²)"] = final_data["surface_salle_de_sejour(m²)"].str.replace(',', '.').astype(float)
final_data["surface(m²)"] = final_data["surface(m²)"].str.replace(',', '.').astype(float)
final_data["terrain_de(m²)"] = final_data["terrain_de(m²)"].str.replace(',', '.').astype(float)
final_data["surface_balcon(m²)"] = final_data["surface_balcon(m²)"].str.replace(',', '.').astype(float)
final_data["surface_cave(m²)"] = final_data["surface_cave(m²)"].str.replace(',', '.').astype(float)
final_data['price(€)'] = final_data['price(€)'].str.replace(' ','')
final_data['monthly(€)'] = final_data['monthly(€)'].str.replace(' ','')
final_data = final_data.fillna(0)
final_data.rename({'Diagnostic de performance énergétique(kWhEP/m².an)': 'energy_performance_diagnosis_(kWhEP/m².year)'}, axis=1, inplace=True)
final_data.rename({"Indice d'émission de gaz à effet de serre(kgeqCO2/m².an)": 'Greenhouse_gas_emission(kgeqCO2/m².year)'}, axis=1, inplace=True)
final_data.rename({'terrasse': 'terrace'}, axis=1, inplace=True)
final_data.rename({'vue': 'view'}, axis=1, inplace=True)
final_data.rename({'surface(m²)': 'area(m²)'}, axis=1, inplace=True)
final_data.rename({'piece': 'room'}, axis=1, inplace=True)
final_data.rename({'chambre': 'bedroom'}, axis=1, inplace=True)
final_data.rename({'annee_de_construction': 'year_of_construction'}, axis=1, inplace=True)
final_data.rename({'salle_de_bain': 'bathroom'}, axis=1, inplace=True)
final_data.rename({'salles_deau': 'shower_room'}, axis=1, inplace=True)
final_data.rename({'surface_salle_de_sejour(m²)': 'living_room_area(m²)'}, axis=1, inplace=True)
final_data.rename({'terrain_de(m²)': 'land(m²)'}, axis=1, inplace=True)
final_data.rename({'cave': 'cellar'}, axis=1, inplace=True)
final_data.rename({'gardien': 'guardian'}, axis=1, inplace=True)
final_data.rename({'ascenseur': 'elevator'}, axis=1, inplace=True)
final_data.rename({'batiment_de_x_étage': 'x_story_building'}, axis=1, inplace=True)
final_data.rename({'num_etage': 'floor_number'}, axis=1, inplace=True)
final_data.rename({'rangements': 'storage'}, axis=1, inplace=True)
final_data.rename({'une_entree': 'an_entrance'}, axis=1, inplace=True)
final_data.rename({'salle_de_sejour': 'living_room'}, axis=1, inplace=True)
final_data.rename({'interphone': 'intercom'}, axis=1, inplace=True)
final_data.rename({'piscine': 'swimming_pool'}, axis=1, inplace=True)
final_data.rename({'cheminee': 'fireplace'}, axis=1, inplace=True)
final_data.rename({'calme': 'calm'}, axis=1, inplace=True)
final_data.rename({'travaux': 'works'}, axis=1, inplace=True)
final_data.rename({'travaux_a_prevoir': 'work_needed'}, axis=1, inplace=True)
final_data.rename({'refait_a_neuf': 'good_as_new'}, axis=1, inplace=True)
final_data.rename({'salle_a_manger': 'dining_room'}, axis=1, inplace=True)
final_data.rename({'adapte_pmr': 'adapted_PMR'}, axis=1, inplace=True)
final_data.rename({'terrain_constructible': 'building_land'}, axis=1, inplace=True)
final_data.rename({'viabilise': 'serviced'}, axis=1, inplace=True)
final_data.rename({'surface_balcon(m²)': 'balcony_area(m²)'}, axis=1, inplace=True)
final_data.rename({'nombre_balcon': 'number_of_balconies'}, axis=1, inplace=True)
final_data.rename({'surface_cave(m²)': 'cellar_area(m²)'}, axis=1, inplace=True)
final_data.rename({'alarme': 'alarm'}, axis=1, inplace=True)
final_data.rename({'meuble': 'furnished'}, axis=1, inplace=True)
final_data.rename({'toilettes': 'bathroom'}, axis=1, inplace=True)
final_data.rename({'toilette_separee': 'separate_toilet'}, axis=1, inplace=True)
final_data.rename({'cuisine_separee': 'separate_kitchen'}, axis=1, inplace=True)
final_data.rename({'cuisine_aucune': 'kitchen_none'}, axis=1, inplace=True)
final_data.rename({'cuisine_americaine': 'american_kitchen'}, axis=1, inplace=True)
final_data.rename({'cuisine_equipee': 'equipped_kitchen'}, axis=1, inplace=True)
final_data.rename({'cuisine_coin_cuisine': 'kitchen_area'}, axis=1, inplace=True)
final_data.rename({'orientation_nord': 'north_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_est': 'east_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_ouest': 'west_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_sud': 'south_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Sud_Ouest': 'south_west_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Sud_Est': 'south_east_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Nord_Ouest': 'north_west_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Nord_Est': 'north_east_orientation'}, axis=1, inplace=True)
final_data.rename({'chauffage_radiateur': 'heating_radiator'}, axis=1, inplace=True)
final_data.rename({'chauffage_gaz': 'gaz_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_mixte': 'mixed_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_electrique': 'electric_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_fuel': 'fuel_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_central': 'central_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_individuel': 'individual_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_sol': 'floor_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_collectif': 'communal_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_climatisation': 'heating_air_conditioning'}, axis=1, inplace=True)
final_data.rename({'chauffage_reversible': 'reversible_heating'}, axis=1, inplace=True)
final_data.rename({'Hôtel particulier': 'mansion'}, axis=1, inplace=True)
final_data.rename({'Immeuble': 'apartment_building'}, axis=1, inplace=True)
final_data.rename({'Local commercial': 'commercial_property'}, axis=1, inplace=True)
final_data.rename({'Loft/Atelier/Surface': 'loft/workshop/area'}, axis=1, inplace=True)
final_data.rename({'Maison / Villa': 'house/villa'}, axis=1, inplace=True)
final_data.rename({'Terrain': 'field'}, axis=1, inplace=True)
final_data.rename({'Acheter': 'for_sale'}, axis=1, inplace=True)
final_data.rename({'Situation campagne': 'countryside'}, axis=1, inplace=True)
final_data.rename({'Situation mer': 'sea'}, axis=1, inplace=True)
final_data.rename({'Situation ville': 'city'}, axis=1, inplace=True)
final_data.rename({'Situation montagne': 'mountain'}, axis=1, inplace=True)
final_data.rename({'Appartement': 'appartement'}, axis=1, inplace=True)
final_data.rename({'Château': 'chateau'}, axis=1, inplace=True)

In [513]:
final_data

,category,price(€),monthly(€),description,energy_performance_diagnosis_(kWhEP/m².year),Greenhouse_gas_emission(kgeqCO2/m².year),type,terrace,view,area(m²),...,electric_heating,fuel_heating,central_heating,individual_heating,floor_heating,communal_heating,heating_air_conditioning,reversible_heating,region_1,region_2
0,Maison / Villa,349500,1449,Belle maison en sous/bassement meulière très b...,150.0,35.0,Acheter,1,0,105.00,...,0,0,0,1,0,0,0,0,Vigneux-sur-Seine,Le Lac-Briques Rouges
1,Maison / Villa,335000,1389,Idéalement situé entre Clermont l'Hérault et L...,0.0,0.0,Acheter,1,0,185.00,...,0,0,0,0,0,0,0,0,Clermont-l Herault,Centre Ville
2,Maison / Villa,2490000,10270,Superbe Villa dans les hauteurs de Nice/Villef...,99.0,19.0,Acheter,0,1,220.00,...,0,1,1,0,0,0,0,0,Nice,Vinaigrier
3,Maison / Villa,356000,1476,"A découvrir à 5km de Gouvieux, maison ancienne...",0.0,0.0,Acheter,0,0,130.00,...,0,0,0,1,0,0,0,0,Gouvieux,Sud
4,Maison / Villa,388500,1610,MAISON INDIVIDUELLE DE 6 PIÈCES A VENDRE A PLA...,214.0,11.0,Acheter,1,0,102.00,...,1,0,0,0,0,0,0,0,Plaisir,Centre Ville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,Maison / Villa,148000,619,0,216.0,11.0,Acheter,1,0,127.00,...,1,0,0,0,0,0,0,0,Villeparisis,0
1988,Maison / Villa,75240,317,0,305.0,0.0,Acheter,0,0,140.00,...,0,0,0,1,0,0,0,0,Carnac,0
1989,Appartement,375000,1554,0,167.0,7.0,Acheter,1,0,72.45,...,1,0,0,1,0,0,0,0,Mandelieu-la-Napoule,0
1990,Appartement,520000,2152,0,125.0,3.0,Acheter,1,0,110.00,...,0,0,0,1,0,0,0,0,Hyeres,0
1991,Appartement,213300,888,0,153.0,33.0,Acheter,0,0,56.00,...,0,0,0,0,0,1,0,0,Torcy,0

In [514]:
final_data['price(€)'] = final_data['price(€)'].astype('str')
final_data['price(€)'] = final_data['price(€)'].str.replace('\xa0','')
final_data['monthly(€)'] = final_data['monthly(€)'].astype('str')
final_data['monthly(€)'] = final_data['monthly(€)'].str.replace('\xa0','')

for i in range (final_data.shape[0]):
    final_data.loc[i, "price(€)"] = int(final_data["price(€)"].iloc[i])
    final_data.loc[i, "monthly(€)"] = int(final_data["monthly(€)"].iloc[i])

In [515]:
final_data

,category,price(€),monthly(€),description,energy_performance_diagnosis_(kWhEP/m².year),Greenhouse_gas_emission(kgeqCO2/m².year),type,terrace,view,area(m²),...,electric_heating,fuel_heating,central_heating,individual_heating,floor_heating,communal_heating,heating_air_conditioning,reversible_heating,region_1,region_2
0,Maison / Villa,349500,1449,Belle maison en sous/bassement meulière très b...,150.0,35.0,Acheter,1,0,105.00,...,0,0,0,1,0,0,0,0,Vigneux-sur-Seine,Le Lac-Briques Rouges
1,Maison / Villa,335000,1389,Idéalement situé entre Clermont l'Hérault et L...,0.0,0.0,Acheter,1,0,185.00,...,0,0,0,0,0,0,0,0,Clermont-l Herault,Centre Ville
2,Maison / Villa,2490000,10270,Superbe Villa dans les hauteurs de Nice/Villef...,99.0,19.0,Acheter,0,1,220.00,...,0,1,1,0,0,0,0,0,Nice,Vinaigrier
3,Maison / Villa,356000,1476,"A découvrir à 5km de Gouvieux, maison ancienne...",0.0,0.0,Acheter,0,0,130.00,...,0,0,0,1,0,0,0,0,Gouvieux,Sud
4,Maison / Villa,388500,1610,MAISON INDIVIDUELLE DE 6 PIÈCES A VENDRE A PLA...,214.0,11.0,Acheter,1,0,102.00,...,1,0,0,0,0,0,0,0,Plaisir,Centre Ville
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,Maison / Villa,148000,619,0,216.0,11.0,Acheter,1,0,127.00,...,1,0,0,0,0,0,0,0,Villeparisis,0
1988,Maison / Villa,75240,317,0,305.0,0.0,Acheter,0,0,140.00,...,0,0,0,1,0,0,0,0,Carnac,0
1989,Appartement,375000,1554,0,167.0,7.0,Acheter,1,0,72.45,...,1,0,0,1,0,0,0,0,Mandelieu-la-Napoule,0
1990,Appartement,520000,2152,0,125.0,3.0,Acheter,1,0,110.00,...,0,0,0,1,0,0,0,0,Hyeres,0
1991,Appartement,213300,888,0,153.0,33.0,Acheter,0,0,56.00,...,0,0,0,0,0,1,0,0,Torcy,0

In [516]:
final_data.to_csv("./final_unextracted_data.csv", index=False)

In [517]:
c1 = pd.get_dummies(full_data.category)
c2 = pd.get_dummies(full_data.type)
c3 = pd.get_dummies(full_data.situation)
c3 = c3.drop('0', 1)
c4 = pd.get_dummies(full_data.region_2)
c4 = c4.drop('0', 1)
c5 = pd.get_dummies(full_data.region_1)

merged = pd.concat([c2, full_data, c1, c3, c5, c4], axis='columns')
final_data = merged.drop(['category', 'localite', 'type', 'situation', 'region_1', 'region_2'], axis='columns')

In [518]:
final_data

,Acheter,price(€),monthly(€),description,Diagnostic de performance énergétique(kWhEP/m².an),Indice d'émission de gaz à effet de serre(kgeqCO2/m².an),terrasse,vue,surface(m²),piece,...,ZAC Saint Sebastien,Zone Agricole,Zone Industrielle,Zone Industrielle du Prat,Zone Nord Est Urbaine,Zone Ouest Urbaine,Zone Pavillonnaire,Zone Pietonne,Zone Rurale Nord,Île de Nantes
0,1,349500,1 449,Belle maison en sous/bassement meulière très b...,150.0,35.0,1,0,105,5,...,0,0,0,0,0,0,0,0,0,0
1,1,335000,1 389,Idéalement situé entre Clermont l'Hérault et L...,NaN,NaN,1,0,185,5,...,0,0,0,0,0,0,0,0,0,0
2,1,2490000,10 270,Superbe Villa dans les hauteurs de Nice/Villef...,99.0,19.0,0,1,220,5,...,0,0,0,0,0,0,0,0,0,0
3,1,356000,1 476,"A découvrir à 5km de Gouvieux, maison ancienne...",NaN,NaN,0,0,130,5,...,0,0,0,0,0,0,0,0,0,0
4,1,388500,1 610,MAISON INDIVIDUELLE DE 6 PIÈCES A VENDRE A PLA...,214.0,11.0,1,0,102,6,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,1,148000,619,NaN,216.0,11.0,1,0,127,5,...,0,0,0,0,0,0,0,0,0,0
1988,1,75240,317,NaN,305.0,NaN,0,0,140,5,...,0,0,0,0,0,0,0,0,0,0
1989,1,375000,1 554,NaN,167.0,7.0,1,0,"72,45",3,...,0,0,0,0,0,0,0,0,0,0
1990,1,520000,2 152,NaN,125.0,3.0,1,0,110,4,...,0,0,0,0,0,0,0,0,0,0
1991,1,213300,888,NaN,153.0,33.0,0,0,56,3,...,0,0,0,0,0,0,0,0,0,0

In [519]:
final_data['price(€)'] = final_data['price(€)'].astype('str')
final_data['price(€)'] = final_data['price(€)'].str.replace(' €','')
final_data["surface_salle_de_sejour(m²)"] = final_data["surface_salle_de_sejour(m²)"].str.replace(',', '.').astype(float)
final_data["surface(m²)"] = final_data["surface(m²)"].str.replace(',', '.').astype(float)
final_data["terrain_de(m²)"] = final_data["terrain_de(m²)"].str.replace(',', '.').astype(float)
final_data["surface_balcon(m²)"] = final_data["surface_balcon(m²)"].str.replace(',', '.').astype(float)
final_data["surface_cave(m²)"] = final_data["surface_cave(m²)"].str.replace(',', '.').astype(float)
final_data['price(€)'] = final_data['price(€)'].str.replace(' ','')
final_data['monthly(€)'] = final_data['monthly(€)'].astype('str')
final_data['monthly(€)'] = final_data['monthly(€)'].str.replace(' ','')

final_data['price(€)'] = final_data['price(€)'].str.replace('\xa0','')
final_data['monthly(€)'] = final_data['monthly(€)'].str.replace('\xa0','')

for i in range (final_data.shape[0]):
    final_data.loc[i, "price(€)"] = int(final_data["price(€)"].iloc[i])
    final_data.loc[i, "monthly(€)"] = int(final_data["monthly(€)"].iloc[i])

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

In [520]:
final_data

,Acheter,price(€),monthly(€),description,Diagnostic de performance énergétique(kWhEP/m².an),Indice d'émission de gaz à effet de serre(kgeqCO2/m².an),terrasse,vue,surface(m²),piece,...,ZAC Saint Sebastien,Zone Agricole,Zone Industrielle,Zone Industrielle du Prat,Zone Nord Est Urbaine,Zone Ouest Urbaine,Zone Pavillonnaire,Zone Pietonne,Zone Rurale Nord,Île de Nantes
0,1,349500,1449,Belle maison en sous/bassement meulière très b...,150.0,35.0,1,0,105.00,5,...,0,0,0,0,0,0,0,0,0,0
1,1,335000,1389,Idéalement situé entre Clermont l'Hérault et L...,NaN,NaN,1,0,185.00,5,...,0,0,0,0,0,0,0,0,0,0
2,1,2490000,10270,Superbe Villa dans les hauteurs de Nice/Villef...,99.0,19.0,0,1,220.00,5,...,0,0,0,0,0,0,0,0,0,0
3,1,356000,1476,"A découvrir à 5km de Gouvieux, maison ancienne...",NaN,NaN,0,0,130.00,5,...,0,0,0,0,0,0,0,0,0,0
4,1,388500,1610,MAISON INDIVIDUELLE DE 6 PIÈCES A VENDRE A PLA...,214.0,11.0,1,0,102.00,6,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,1,148000,619,NaN,216.0,11.0,1,0,127.00,5,...,0,0,0,0,0,0,0,0,0,0
1988,1,75240,317,NaN,305.0,NaN,0,0,140.00,5,...,0,0,0,0,0,0,0,0,0,0
1989,1,375000,1554,NaN,167.0,7.0,1,0,72.45,3,...,0,0,0,0,0,0,0,0,0,0
1990,1,520000,2152,NaN,125.0,3.0,1,0,110.00,4,...,0,0,0,0,0,0,0,0,0,0
1991,1,213300,888,NaN,153.0,33.0,0,0,56.00,3,...,0,0,0,0,0,0,0,0,0,0

In [521]:
final_data = final_data.fillna(0)

In [522]:
final_data.rename({'Diagnostic de performance énergétique(kWhEP/m².an)': 'energy_performance_diagnosis_(kWhEP/m².year)'}, axis=1, inplace=True)
final_data.rename({"Indice d'émission de gaz à effet de serre(kgeqCO2/m².an)": 'Greenhouse_gas_emission(kgeqCO2/m².year)'}, axis=1, inplace=True)
final_data.rename({'terrasse': 'terrace'}, axis=1, inplace=True)
final_data.rename({'vue': 'view'}, axis=1, inplace=True)
final_data.rename({'surface(m²)': 'area(m²)'}, axis=1, inplace=True)
final_data.rename({'piece': 'room'}, axis=1, inplace=True)
final_data.rename({'chambre': 'bedroom'}, axis=1, inplace=True)
final_data.rename({'annee_de_construction': 'year_of_construction'}, axis=1, inplace=True)
final_data.rename({'salle_de_bain': 'bathroom'}, axis=1, inplace=True)
final_data.rename({'salles_deau': 'shower_room'}, axis=1, inplace=True)
final_data.rename({'surface_salle_de_sejour(m²)': 'living_room_area(m²)'}, axis=1, inplace=True)
final_data.rename({'terrain_de(m²)': 'land(m²)'}, axis=1, inplace=True)
final_data.rename({'cave': 'cellar'}, axis=1, inplace=True)
final_data.rename({'gardien': 'guardian'}, axis=1, inplace=True)
final_data.rename({'ascenseur': 'elevator'}, axis=1, inplace=True)
final_data.rename({'batiment_de_x_étage': 'x_story_building'}, axis=1, inplace=True)
final_data.rename({'num_etage': 'floor_number'}, axis=1, inplace=True)
final_data.rename({'rangements': 'storage'}, axis=1, inplace=True)
final_data.rename({'une_entree': 'an_entrance'}, axis=1, inplace=True)
final_data.rename({'salle_de_sejour': 'living_room'}, axis=1, inplace=True)
final_data.rename({'interphone': 'intercom'}, axis=1, inplace=True)
final_data.rename({'piscine': 'swimming_pool'}, axis=1, inplace=True)
final_data.rename({'cheminee': 'fireplace'}, axis=1, inplace=True)
final_data.rename({'calme': 'calm'}, axis=1, inplace=True)
final_data.rename({'travaux': 'works'}, axis=1, inplace=True)
final_data.rename({'travaux_a_prevoir': 'work_needed'}, axis=1, inplace=True)
final_data.rename({'refait_a_neuf': 'good_as_new'}, axis=1, inplace=True)
final_data.rename({'salle_a_manger': 'dining_room'}, axis=1, inplace=True)
final_data.rename({'adapte_pmr': 'adapted_PMR'}, axis=1, inplace=True)
final_data.rename({'terrain_constructible': 'building_land'}, axis=1, inplace=True)
final_data.rename({'viabilise': 'serviced'}, axis=1, inplace=True)
final_data.rename({'surface_balcon(m²)': 'balcony_area(m²)'}, axis=1, inplace=True)
final_data.rename({'nombre_balcon': 'number_of_balconies'}, axis=1, inplace=True)
final_data.rename({'surface_cave(m²)': 'cellar_area(m²)'}, axis=1, inplace=True)
final_data.rename({'alarme': 'alarm'}, axis=1, inplace=True)
final_data.rename({'meuble': 'furnished'}, axis=1, inplace=True)
final_data.rename({'toilettes': 'bathroom'}, axis=1, inplace=True)
final_data.rename({'toilette_separee': 'separate_toilet'}, axis=1, inplace=True)
final_data.rename({'cuisine_separee': 'separate_kitchen'}, axis=1, inplace=True)
final_data.rename({'cuisine_aucune': 'kitchen_none'}, axis=1, inplace=True)
final_data.rename({'cuisine_americaine': 'american_kitchen'}, axis=1, inplace=True)
final_data.rename({'cuisine_equipee': 'equipped_kitchen'}, axis=1, inplace=True)
final_data.rename({'cuisine_coin_cuisine': 'kitchen_area'}, axis=1, inplace=True)
final_data.rename({'orientation_nord': 'north_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_est': 'east_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_ouest': 'west_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_sud': 'south_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Sud_Ouest': 'south_west_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Sud_Est': 'south_east_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Nord_Ouest': 'north_west_orientation'}, axis=1, inplace=True)
final_data.rename({'orientation_Nord_Est': 'north_east_orientation'}, axis=1, inplace=True)
final_data.rename({'chauffage_radiateur': 'heating_radiator'}, axis=1, inplace=True)
final_data.rename({'chauffage_gaz': 'gaz_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_mixte': 'mixed_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_electrique': 'electric_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_fuel': 'fuel_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_central': 'central_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_individuel': 'individual_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_sol': 'floor_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_collectif': 'communal_heating'}, axis=1, inplace=True)
final_data.rename({'chauffage_climatisation': 'heating_air_conditioning'}, axis=1, inplace=True)
final_data.rename({'chauffage_reversible': 'reversible_heating'}, axis=1, inplace=True)
final_data.rename({'Hôtel particulier': 'mansion'}, axis=1, inplace=True)
final_data.rename({'Immeuble': 'apartment_building'}, axis=1, inplace=True)
final_data.rename({'Local commercial': 'commercial_property'}, axis=1, inplace=True)
final_data.rename({'Loft/Atelier/Surface': 'loft/workshop/area'}, axis=1, inplace=True)
final_data.rename({'Maison / Villa': 'house/villa'}, axis=1, inplace=True)
final_data.rename({'Terrain': 'field'}, axis=1, inplace=True)
final_data.rename({'Acheter': 'for_sale'}, axis=1, inplace=True)
final_data.rename({'Situation campagne': 'countryside'}, axis=1, inplace=True)
final_data.rename({'Situation mer': 'sea'}, axis=1, inplace=True)
final_data.rename({'Situation ville': 'city'}, axis=1, inplace=True)
final_data.rename({'Situation montagne': 'mountain'}, axis=1, inplace=True)
final_data.rename({'Appartement': 'appartement'}, axis=1, inplace=True)
final_data.rename({'Château': 'chateau'}, axis=1, inplace=True)

In [523]:
final_data = final_data.drop('Parking', axis=1)

In [524]:
final_data

,for_sale,price(€),monthly(€),description,energy_performance_diagnosis_(kWhEP/m².year),Greenhouse_gas_emission(kgeqCO2/m².year),terrace,view,area(m²),room,...,ZAC Saint Sebastien,Zone Agricole,Zone Industrielle,Zone Industrielle du Prat,Zone Nord Est Urbaine,Zone Ouest Urbaine,Zone Pavillonnaire,Zone Pietonne,Zone Rurale Nord,Île de Nantes
0,1,349500,1449,Belle maison en sous/bassement meulière très b...,150.0,35.0,1,0,105.00,5,...,0,0,0,0,0,0,0,0,0,0
1,1,335000,1389,Idéalement situé entre Clermont l'Hérault et L...,0.0,0.0,1,0,185.00,5,...,0,0,0,0,0,0,0,0,0,0
2,1,2490000,10270,Superbe Villa dans les hauteurs de Nice/Villef...,99.0,19.0,0,1,220.00,5,...,0,0,0,0,0,0,0,0,0,0
3,1,356000,1476,"A découvrir à 5km de Gouvieux, maison ancienne...",0.0,0.0,0,0,130.00,5,...,0,0,0,0,0,0,0,0,0,0
4,1,388500,1610,MAISON INDIVIDUELLE DE 6 PIÈCES A VENDRE A PLA...,214.0,11.0,1,0,102.00,6,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1987,1,148000,619,0,216.0,11.0,1,0,127.00,5,...,0,0,0,0,0,0,0,0,0,0
1988,1,75240,317,0,305.0,0.0,0,0,140.00,5,...,0,0,0,0,0,0,0,0,0,0
1989,1,375000,1554,0,167.0,7.0,1,0,72.45,3,...,0,0,0,0,0,0,0,0,0,0
1990,1,520000,2152,0,125.0,3.0,1,0,110.00,4,...,0,0,0,0,0,0,0,0,0,0
1991,1,213300,888,0,153.0,33.0,0,0,56.00,3,...,0,0,0,0,0,0,0,0,0,0

In [525]:
final_data.to_csv("./final_clean_data.csv", index=False)

In [526]:
data = pd.read_csv("./final_clean_data.csv")
data.shape

(1992, 1606)